version: "3.8"

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 8080:8080
    volumes:
      - .:/go/src
    depends_on:
      - db

  db:
    container_name: db
    image: mysql:8.0
    tty: true
    ports:
      - 3306:3306
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/mysql
      - type: bind
        source: ./init_shell
        target: /docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: product_admin_api
      MYSQL_USER: test_user
      MYSQL_PASSWORD: password

volumes:
  db-data:
    driver: local
